/**
 * Cotect User Endpoints
 * User endpoints REST API for cotect project.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CaseSymptom model module.
* @module model/CaseSymptom
* @version 0.1.0
*/
export default class CaseSymptom {
    /**
    * Constructs a new <code>CaseSymptom</code>.
    * @alias module:model/CaseSymptom
    * @class
    * @param symptomName {String} 
    */

    constructor(symptomName) {
        
        
        this['symptom_name'] = symptomName;
        
    }

    /**
    * Constructs a <code>CaseSymptom</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CaseSymptom} obj Optional instance to populate.
    * @return {module:model/CaseSymptom} The populated <code>CaseSymptom</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CaseSymptom();
                        
            
            if (data.hasOwnProperty('symptom_name')) {
                obj['symptom_name'] = ApiClient.convertToType(data['symptom_name'], 'String');
            }
            if (data.hasOwnProperty('report_date')) {
                obj['report_date'] = ApiClient.convertToType(data['report_date'], 'Date');
            }
            if (data.hasOwnProperty('severity')) {
                obj['severity'] = ApiClient.convertToType(data['severity'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} symptom_name
    */
    symptom_name = undefined;
    /**
    * @member {Date} report_date
    */
    report_date = undefined;
    /**
    * @member {String} severity
    */
    severity = undefined;




}
