/**
 * Cotect User Endpoints
 * User endpoints REST API for cotect project.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CaseContact model module.
 * @module model/CaseContact
 * @version 0.1.2
 */
class CaseContact {
    /**
     * Constructs a new <code>CaseContact</code>.
     * @alias module:model/CaseContact
     * @param phoneNumber {String} 
     */
    constructor(phoneNumber) { 
        
        CaseContact.initialize(this, phoneNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phoneNumber) { 
        obj['phone_number'] = phoneNumber;
    }

    /**
     * Constructs a <code>CaseContact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CaseContact} obj Optional instance to populate.
     * @return {module:model/CaseContact} The populated <code>CaseContact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CaseContact();

            if (data.hasOwnProperty('phone_number')) {
                obj['phone_number'] = ApiClient.convertToType(data['phone_number'], 'String');
            }
            if (data.hasOwnProperty('contact_dates')) {
                obj['contact_dates'] = ApiClient.convertToType(data['contact_dates'], ['Date']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} phone_number
 */
CaseContact.prototype['phone_number'] = undefined;

/**
 * @member {Array.<Date>} contact_dates
 */
CaseContact.prototype['contact_dates'] = undefined;






export default CaseContact;

