/**
 * Cotect User Endpoints
 * User endpoints REST API for cotect project.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CaseContact model module.
* @module model/CaseContact
* @version 0.1.0
*/
export default class CaseContact {
    /**
    * Constructs a new <code>CaseContact</code>.
    * @alias module:model/CaseContact
    * @class
    * @param phoneNumber {String} 
    */

    constructor(phoneNumber) {
        
        
        this['phone_number'] = phoneNumber;
        
    }

    /**
    * Constructs a <code>CaseContact</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CaseContact} obj Optional instance to populate.
    * @return {module:model/CaseContact} The populated <code>CaseContact</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CaseContact();
                        
            
            if (data.hasOwnProperty('phone_number')) {
                obj['phone_number'] = ApiClient.convertToType(data['phone_number'], 'String');
            }
            if (data.hasOwnProperty('contact_date')) {
                obj['contact_date'] = ApiClient.convertToType(data['contact_date'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {String} phone_number
    */
    phone_number = undefined;
    /**
    * @member {Date} contact_date
    */
    contact_date = undefined;




}
